---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sample-app-prod
  namespace: prod
spec:
  releaseName: sample-app-prod
  targetNamespace: prod
  storageNamespace: prod
  interval: 10s
  chart:
    spec:
      chart: nginx-app-helm
      # version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: nginx-app-helm
  values:
    replicaCount: 2
    tag:
    image:
      repository: 647088104484.dkr.ecr.us-east-2.amazonaws.com/nginx-app-prod
      pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
      tag: "prod"
  install: {}
