apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sample-app-homol
  namespace: homol
spec:
  releaseName: sample-app-homol
  targetNamespace: homol
  storageNamespace: homol
  interval: 10s
  chart:
    spec:
      chart: nginx-app-helm
      version: 0.4.0
      sourceRef:
        kind: HelmRepository
        name: nginx-app-helm
  values:
    replicaCount: 2
    image: "647088104484.dkr.ecr.us-east-2.amazonaws.com/nginx-app-homol:59" # {"$imagepolicy": "flux-system:sample-app-homol"}
  install: {}
---
# Flux Specific manifests for image reconciliation
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: sample-app-homol
  namespace: flux-system
spec:
  image: 647088104484.dkr.ecr.us-east-2.amazonaws.com/nginx-app-homol
  interval: 1m0s
---
# Then, use the CRD ImagePolicy to specify which version you want to track.
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: sample-app-homol
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: sample-app-homol # Reference from above manifest
    namespace: flux-system
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: image-update-homol
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: main
  update:
    path: ./apps/homol
    strategy: Setters
