---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: nginx-app-helm
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://github.com/iagobanov/chart-repo/nginx-app-helm-0.1.0.tgz
