---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sample-app
  namespace: flux-system
spec:
  releaseName: sample-app
  targetNamespace: dev
  storageNamespace: dev
  interval: 10s
  chart:
    spec:
      chart: nginx-app-helm
      # version: 5.9.2
      sourceRef:
        kind: HelmRepository
        name: app-chart
  values:
    replicaCount: 2
    tag:
    image:
      repository: 647088104484.dkr.ecr.us-east-2.amazonaws.com/nginx-app-dev
      pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
      tag: "dev"
  install: {}
